#!/bin/sh
#chkconfig: 2345 20 80
#deskription: hehe
source /etc/init.d/functions
start() {
	daemon "python -m SimpleHTTPServer 8080 &"
	return $?
}

stop() {
  killproc python
	return $?	
}

check_status() {
	status $prog >/dev/null 2>&1
}

case "$1" in
	start)
		check_status && echo "error exit" && exit 0
		$1
	;;
	stop)
		check_status && echo "error exit" && exit 0
		$1
	;;
	restart)
		stop
		start
	;;
	status)
		check_status
	;;
	*)
		echo "Usage: $0 {start | stop | status | restart}"
		exit 2
esac
